### ISSUE TITLE
katualueenosa-taulun relaatioissa on ongelmia

### ISSUE THREAD

**Issue by SanttuVP** [GispoCoding/infraO-open#4]
Katualueenosien tuottaminen onnistuu, mutta QGISilla kestää suhteellisen kauan avata katualueenosa-taulun lomake. Jos vertaa viheralueenosaan, tässä menee kauemmin. Alla näytönkaappaus Warning-ilmoituksista:
![image](https://user-images.githubusercontent.com/13584679/233391343-08c68140-486f-43f9-884e-955b85c5818d.png)

**Comment by JuhoErvasti** [comment]
@SanttuVP Siinä kestää kun se lataa noita relaatiokenttiä sinne, tässä riittää kun laittaa katualueenosalle drag and drop designerin päälle niin ei tule turhia kenttiä lomakkeeseen.
